storage: /verdaccio/storage
packages:
  '@useoptic/*':
      access: $all
      publish: $all
  '*/*':
      access: $all
      proxy: npmjs
  '**':
      access: $all
      proxy: npmjs
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
logs:
  - {type: stdout, format: pretty, level: trace}
